export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const SENDING_REQUEST = "SENDING_REQUEST";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";