export const EXISTING_EMAIL = "EXISTING_EMAIL";
export const PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH";
export const NOT_EXSITING_EMAIL = "NOT_EXSITING_EMAIL";
export const DUPLICATE_EMAIL = "DUPLICATE_EMAIL";
export const SERVER_ERROR = "SERVER_ERROR";
